apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::998189017768:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::998189017768:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QCNDU2OX9JQA
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-02T01:05:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1535"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ba3ce1b9-84ac-4f7c-a9e4-f6b19e600320
